version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install cfn-lint
  build:
    commands:
      - echo "Linting scalable-express.yaml..."
      - cfn-lint scalable-express.yaml
artifacts:
  files:
    - scalable-express.yaml
